CREATE TABLE IF NOT EXISTS USERS(
	ID	SERIAL	PRIMARY KEY NOT NULL,
	PRIMER_NOMBRE	VARCHAR	NOT NULL,
	APELLIDO_PAT	VARCHAR	NOT NULL,
	APELLIDO_MAT	VARCHAR	NOT NULL,
	FECHA_NAC	DATE	NOT NULL,
	RFC	VARCHAR	NOT NULL,
	INGRESOS_MENSUALES	INT	NOT NULL,
	DEPENDIENTES	INT	NOT NULL,
	APROBADO	BOOLEAN	NOT NULL
);


INSERT INTO USERS(PRIMER_NOMBRE, APELLIDO_PAT, APELLIDO_MAT, FECHA_NAC, RFC, INGRESOS_MENSUALES, DEPENDIENTES, APROBADO) VALUES (%s, %s, %s, %s, %s, %s, %s, %s) RETURNING ID;